name: Gold Rate Tracker

permissions:
  contents: write

on:
  schedule:
    - cron: "30 6 * * *"
  workflow_dispatch:

jobs:
  run-script:

    runs-on: ubuntu-latest

    env:
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run script
        run: python fetch_gold_rate.py

      - name: Commit updated JSON
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"
          git add gold_rates.json
          git add docs/gold_price_chart.png
          git commit -m "Update gold rate" || echo "No changes"
          git push